allowBuilds:
  '@dep-tree/cli': set this to true or false
  core-js: set this to true or false
  core-js-pure: set this to true or false
  es5-ext: set this to true or false
  esbuild: set this to true or false
minimumReleaseAgeExclude:
  - '@types/react@19.2.15'
  - '@rc-component/async-validator@6.0.0'
  - '@rc-component/form@1.8.3'
  - antd@6.4.4
  - es-toolkit@1.47.1
